import AdminNav from "@/components/admin/AdminNav/adminNav";
export const metadata = {
  title: "Admin dashbouard",
  description: "Generated by shirin joon",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa">
      <body>
        <header>
          <AdminNav />
        </header>
        <main > {children} </main>
      </body>
    </html>
  );
}
