"use client";
import { ThemeProvider } from "flowbite-react";
import { customTheme } from "../styles/them";
export const metadata = {
  title: "admin dashboard",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider theme={customTheme}>
          <div className="flex min-h-screen">
            {/* سایدبار */}
            <aside className="w-1/4 bg-gray-100 border-r p-4">
              <AdminSidebar />
            </aside>

            {/* محتوای اصلی */}
            <main className="flex-1 p-6">{children}</main>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}

// import { useState } from "react";
// import Image from "next/image";
// import Link from "next/link";
// 
// export default function Layout({ children }) {
//   const [isSidebarOpen, setIsSidebarOpen] = useState(false);
//   const [isNotificationsOpen, setIsNotificationsOpen] = useState(false);
//   const [isAppsOpen, setIsAppsOpen] = useState(false);
//   const [isUserMenuOpen, setIsUserMenuOpen] = useState(false);
//   const [isLanguageOpen, setIsLanguageOpen] = useState(false);
//   const [isPagesOpen, setIsPagesOpen] = useState(false);
//   const [isSalesOpen, setIsSalesOpen] = useState(false);
//   const [isAuthOpen, setIsAuthOpen] = useState(false);
// 
//   const toggleSidebar = () => setIsSidebarOpen(!isSidebarOpen);
//   const toggleNotifications = () =>
//     setIsNotificationsOpen(!isNotificationsOpen);
//   const toggleApps = () => setIsAppsOpen(!isAppsOpen);
//   const toggleUserMenu = () => setIsUserMenuOpen(!isUserMenuOpen);
//   const toggleLanguage = () => setIsLanguageOpen(!isLanguageOpen);
//   const togglePages = () => setIsPagesOpen(!isPagesOpen);
//   const toggleSales = () => setIsSalesOpen(!isSalesOpen);
//   const toggleAuth = () => setIsAuthOpen(!isAuthOpen);
// 
//   return (
//     <div className="antialiased bg-gray-50 dark:bg-gray-900 min-h-screen">
//       {/* Navbar */}
//       <nav className="bg-white border-b border-gray-200 px-4 py-2.5 dark:bg-gray-800 dark:border-gray-700 fixed left-0 right-0 top-0 z-50">
//         <div className="flex flex-wrap justify-between items-center">
//           <div className="flex justify-start items-center">
//             <button
//               onClick={toggleSidebar}
//               className="p-2 mr-2 text-gray-600 rounded-lg cursor-pointer md:hidden hover:text-gray-900 hover:bg-gray-100 focus:bg-gray-100 dark:focus:bg-gray-700 focus:ring-2 focus:ring-gray-100 dark:focus:ring-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white"
//             >
//               <svg
//                 className="w-6 h-6"
//                 fill="currentColor"
//                 viewBox="0 0 20 20"
//                 xmlns="http://www.w3.org/2000/svg"
//               >
//                 <path
//                   fillRule="evenodd"
//                   d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h6a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z"
//                   clipRule="evenodd"
//                 ></path>
//               </svg>
//               <span className="sr-only">Toggle sidebar</span>
//             </button>
//             <Link
//               href="https://flowbite.com"
//               className="flex items-center justify-between mr-4"
//             >
//               <Image
//                 src="https://flowbite.s3.amazonaws.com/logo.svg"
//                 width={32}
//                 height={32}
//                 alt="Flowbite Logo"
//                 className="mr-3"
//               />
//               <span className="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">
//                 Flowbite
//               </span>
//             </Link>
//             <div className="hidden md:block md:pl-2">
//               <div className="relative md:w-64">
//                 <div className="flex absolute inset-y-0 left-0 items-center pl-3 pointer-events-none">
//                   <svg
//                     className="w-5 h-5 text-gray-500 dark:text-gray-400"
//                     fill="currentColor"
//                     viewBox="0 0 20 20"
//                     xmlns="http://www.w3.org/2000/svg"
//                   >
//                     <path
//                       fillRule="evenodd"
//                       d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z"
//                       clipRule="evenodd"
//                     ></path>
//                   </svg>
//                 </div>
//                 <input
//                   type="text"
//                   name="email"
//                   className="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full pl-10 p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
//                   placeholder="Search"
//                 />
//               </div>
//             </div>
//           </div>
//           <div className="flex items-center lg:order-2">
//             <button
//               onClick={toggleNotifications}
//               className="p-2 mr-1 text-gray-500 rounded-lg hover:text-gray-900 hover:bg-gray-100 dark:text-gray-400 dark:hover:text-white dark:hover:bg-gray-700 focus:ring-4 focus:ring-gray-300 dark:focus:ring-gray-600"
//             >
//               <svg
//                 className="w-6 h-6"
//                 fill="currentColor"
//                 viewBox="0 0 20 20"
//                 xmlns="http://www.w3.org/2000/svg"
//               >
//                 <path d="M10 2a6 6 0 00-6 6v3.586l-.707.707A1 1 0 004 14h12a1 1 0 00.707-1.707L16 11.586V8a6 6 0 00-6-6zM10 18a3 3 0 01-3-3h6a3 3 0 01-3 3z"></path>
//               </svg>
//               <span className="sr-only">View notifications</span>
//             </button>
//             {isNotificationsOpen && (
//               <div className="absolute top-12 right-0 z-50 my-4 max-w-sm text-base list-none bg-white rounded divide-y divide-gray-100 shadow-lg dark:divide-gray-600 dark:bg-gray-700 rounded-xl">
//                 <div className="block py-2 px-4 text-base font-medium text-center text-gray-700 bg-gray-50 dark:bg-gray-600 dark:text-gray-300">
//                   Notifications
//                 </div>
//                 {/* Notification items */}
//                 <div>
//                   <Link
//                     href="#"
//                     className="flex py-3 px-4 border-b hover:bg-gray-100 dark:hover:bg-gray-600 dark:border-gray-600"
//                   >
//                     <div className="flex-shrink-0">
//                       <Image
//                         src="https://flowbite.s3.amazonaws.com/blocks/marketing-ui/avatars/bonnie-green.png"
//                         width={44}
//                         height={44}
//                         alt="Bonnie Green avatar"
//                         className="rounded-full"
//                       />
//                       <div className="flex absolute justify-center items-center ml-6 -mt-5 w-5 h-5 rounded-full border border-white bg-blue-700 dark:border-gray-700">
//                         <svg
//                           className="w-3 h-3 text-white"
//                           fill="currentColor"
//                           viewBox="0 0 20 20"
//                           xmlns="http://www.w3.org/2000/svg"
//                         >
//                           <path d="M8.707 7.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l2-2a1 1 0 00-1.414-1.414L11 7.586V3a1 1 0 10-2 0v4.586l-.293-.293z"></path>
//                           <path d="M3 5a2 2 0 012-2h1a1 1 0 010 2H5v7h2l1 2h4l1-2h2V5h-1a1 1 0 110-2h1a2 2 0 012 2v10a2 2 0 01-2 2H5a2 2 0 01-2-2V5z"></path>
//                         </svg>
//                       </div>
//                     </div>
//                     <div className="pl-3 w-full">
//                       <div className="text-gray-500 font-normal text-sm mb-1.5 dark:text-gray-400">
//                         New message from{" "}
//                         <span className="font-semibold text-gray-900 dark:text-white">
//                           Bonnie Green
//                         </span>
//                         : "Hey, what's up? All set for the presentation?"
//                       </div>
//                       <div className="text-xs font-medium text-blue-600 dark:text-blue-500">
//                         a few moments ago
//                       </div>
//                     </div>
//                   </Link>
//                   {/* Add other notification items similarly */}
//                 </div>
//                 <Link
//                   href="#"
//                   className="block py-2 text-md font-medium text-center text-gray-900 bg-gray-50 hover:bg-gray-100 dark:bg-gray-600 dark:text-white dark:hover:underline"
//                 >
//                   <div className="inline-flex items-center">
//                     <svg
//                       className="mr-2 w-4 h-4 text-gray-500 dark:text-gray-400"
//                       fill="currentColor"
//                       viewBox="0 0 20 20"
//                       xmlns="http://www.w3.org/2000/svg"
//                     >
//                       <path d="M10 12a2 2 0 100-4 2 2 0 000 4z"></path>
//                       <path
//                         fillRule="evenodd"
//                         d="M.458 10C1.732 5.943 5.522 3 10 3s8.268 2.943 9.542 7c-1.274 4.057-5.064 7-9.542 7S1.732 14.057.458 10zM14 10a4 4 0 11-8 0 4 4 0 018 0z"
//                         clipRule="evenodd"
//                       ></path>
//                     </svg>
//                     View all
//                   </div>
//                 </Link>
//               </div>
//             )}
//             <button
//               onClick={toggleApps}
//               className="p-2 text-gray-500 rounded-lg hover:text-gray-900 hover:bg-gray-100 dark:text-gray-400 dark:hover:text-white dark:hover:bg-gray-700 focus:ring-4 focus:ring-gray-300 dark:focus:ring-gray-600"
//             >
//               <svg
//                 className="w-6 h-6"
//                 fill="currentColor"
//                 viewBox="0 0 20 20"
//                 xmlns="http://www.w3.org/2000/svg"
//               >
//                 <path d="M5 3a2 2 0 00-2 2v2a2 2 0 002 2h2a2 2 0 002-2V5a2 2 0 00-2-2H5zM5 11a2 2 0 00-2 2v2a2 2 0 002 2h2a2 2 0 002-2v-2a2 2 0 00-2-2H5zM11 5a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2V5zM11 13a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2v-2z"></path>
//               </svg>
//               <span className="sr-only">View notifications</span>
//             </button>
//             {isAppsOpen && (
//               <div className="absolute top-12 right-0 z-50 my-4 max-w-sm text-base list-none bg-white rounded divide-y divide-gray-100 shadow-lg dark:bg-gray-700 dark:divide-gray-600 rounded-xl">
//                 <div className="block py-2 px-4 text-base font-medium text-center text-gray-700 bg-gray-50 dark:bg-gray-600 dark:text-gray-300">
//                   Apps
//                 </div>
//                 <div className="grid grid-cols-3 gap-4 p-4">
//                   <Link
//                     href="#"
//                     className="block p-4 text-center rounded-lg hover:bg-gray-100 dark:hover:bg-gray-600 group"
//                   >
//                     <svg
//                       className="mx-auto mb-1 w-7 h-7 text-gray-400 group-hover:text-gray-500 dark:text-gray-400 dark:group-hover:text-gray-400"
//                       fill="currentColor"
//                       viewBox="0 0 20 20"
//                       xmlns="http://www.w3.org/2000/svg"
//                     >
//                       <path
//                         fillRule="evenodd"
//                         d="M10 2a italics 4 4 0 00-4 4v1H5a1 1 0 00-.994.89l-1 9A1 1 0 004 18h12a1 1 0 00.994-1.11l-1-9A1 1 0 0015 7h-1V6a4 4 0 00-4-4zm2 5V6a2 2 0 10-4 0v1h4zm-6 3a1 1 0 112 0 1 1 0 01-2 0zm7-1a1 1 0 100 2 1 1 0 000-2z"
//                         clipRule="evenodd"
//                       ></path>
//                     </svg>
//                     <div className="text-sm text-gray-900 dark:text-white">
//                       Sales
//                     </div>
//                   </Link>
//                   {/* Add other app items similarly */}
//                 </div>
//               </div>
//             )}
//             <button
//               onClick={toggleUserMenu}
//               className="flex mx-3 text-sm bg-gray-800 rounded-full md:mr-0 focus:ring-4 focus:ring-gray-300 dark:focus:ring-gray-600"
//             >
//               <Image
//                 className="w-8 h-8 rounded-full"
//                 src="https://flowbite.s3.amazonaws.com/blocks/marketing-ui/avatars/michael-gough.png"
//                 width={32}
//                 height={32}
//                 alt="user photo"
//               />
//               <span className="sr-only">Open user menu</span>
//             </button>
//             {isUserMenuOpen && (
//               <div className="absolute top-12 right-0 z-50 my-4 w-56 text-base list-none bg-white rounded divide-y divide-gray-100 shadow dark:bg-gray-700 dark:divide-gray-600 rounded-xl">
//                 <div className="py-3 px-4">
//                   <span className="block text-sm font-semibold text-gray-900 dark:text-white">
//                     Neil Sims
//                   </span>
//                   <span className="block text-sm text-gray-900 truncate dark:text-white">
//                     name@flowbite.com
//                   </span>
//                 </div>
//                 <ul className="py-1 text-gray-700 dark:text-gray-300">
//                   <li>
//                     <Link
//                       href="#"
//                       className="block py-2 px-4 text-sm hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-400 dark:hover:text-white"
//                     >
//                       My profile
//                     </Link>
//                   </li>
//                   <li>
//                     <Link
//                       href="#"
//                       className="block py-2 px-4 text-sm hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-400 dark:hover:text-white"
//                     >
//                       Account settings
//                     </Link>
//                   </li>
//                 </ul>
//                 <ul className="py-1 text-gray-700 dark:text-gray-300">
//                   <li>
//                     <Link
//                       href="#"
//                       className="flex items-center py-2 px-4 text-sm hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white"
//                     >
//                       <svg
//                         className="mr-2 w-5 h-5 text-gray-400"
//                         fill="currentColor"
//                         viewBox="0 0 20 20"
//                         xmlns="http://www.w3.org/2000/svg"
//                       >
//                         <path
//                           fillRule="evenodd"
//                           d="M3.172 5.172a4 4 0 015.656 0L10 6.343l1.172-1.171a4 4 0 115.656 5.656L10 17.657l-6.828-6.829a4 4 0 010-5.656z"
//                           clipRule="evenodd"
//                         ></path>
//                       </svg>
//                       My likes
//                     </Link>
//                   </li>
//                   {/* Add other user menu items similarly */}
//                 </ul>
//                 <ul className="py-1 text-gray-700 dark:text-gray-300">
//                   <li>
//                     <Link
//                       href="#"
//                       className="block py-2 px-4 text-sm hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white"
//                     >
//                       Sign out
//                     </Link>
//                   </li>
//                 </ul>
//               </div>
//             )}
//           </div>
//         </div>
//       </nav>
// 
//       {/* Sidebar */}
//       <aside
//         className={`fixed top-0 left-0 z-40 w-64 h-screen pt-14 transition-transform ${
//           isSidebarOpen ? "translate-x-0" : "-translate-x-full"
//         } bg-white border-r border-gray-200 md:translate-x-0 dark:bg-gray-800 dark:border-gray-700`}
//       >
//         <div className="overflow-y-auto py-5 px-3 h-full bg-white dark:bg-gray-800">
//           <div className="md:hidden mb-2">
//             <div className="relative">
//               <div className="flex absolute inset-y-0 left-0 items-center pl-3 pointer-events-none">
//                 <svg
//                   className="w-5 h-5 text-gray-500 dark:text-gray-400"
//                   fill="currentColor"
//                   viewBox="0 0 20 20"
//                   xmlns="http://www.w3.org/2000/svg"
//                 >
//                   <path
//                     fillRule="evenodd"
//                     d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z"
//                     clipRule="evenodd"
//                   ></path>
//                 </svg>
//               </div>
//               <input
//                 type="text"
//                 name="search"
//                 className="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full pl-10 p-2 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
//                 placeholder="Search"
//               />
//             </div>
//           </div>
//           <ul className="space-y-2">
//             <li>
//               <Link
//                 href="#"
//                 className="flex items-center p-2 text-base font-medium text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group"
//               >
//                 <svg
//                   className="w-6 h-6 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white"
//                   fill="currentColor"
//                   viewBox="0 0 20 20"
//                   xmlns="http://www.w3.org/2000/svg"
//                 >
//                   <path d="M2 10a8 8 0 018-8v8h8a8 8 0 11-16 0z"></path>
//                   <path d="M12 2.252A8.014 8.014 0 0117.748 8H12V2.252z"></path>
//                 </svg>
//                 <span className="ml-3">Overview</span>
//               </Link>
//             </li>
//             <li>
//               <button
//                 onClick={togglePages}
//                 className="flex items-center p-2 w-full text-base font-medium text-gray-900 rounded-lg transition duration-75 group hover:bg-gray-100 dark:text-white dark:hover:bg-gray-700"
//               >
//                 <svg
//                   className="flex-shrink-0 w-6 h-6 text-gray-500 transition duration-75 group-hover:text-gray-900 dark:text-gray-400 dark:group-hover:text-white"
//                   fill="currentColor"
//                   viewBox="0 0 20 20"
//                   xmlns="http://www.w3.org/2000/svg"
//                 >
//                   <path
//                     fillRule="evenodd"
//                     d="M4 4a2 2 0 012-2h4.586A2 2 0 0112 2.586L15.414 6A2 2 0 0116 7.414V16a2 2 0 01-2 2H6a2 2 0 01-2-2V4zm2 6a1 1 0 011-1h6a1 1 0 110 2H7a1 1 0 01-1-1zm1 3a1 1 0 100 2h6a1 1 0 100-2H7z"
//                     clipRule="evenodd"
//                   ></path>
//                 </svg>
//                 <span className="flex-1 ml-3 text-left whitespace-nowrap">
//                   Pages
//                 </span>
//                 <svg
//                   className="w-6 h-6"
//                   fill="currentColor"
//                   viewBox="0 0 20 20"
//                   xmlns="http://www.w3.org/2000/svg"
//                 >
//                   <path
//                     fillRule="evenodd"
//                     d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"
//                     clipRule="evenodd"
//                   ></path>
//                 </svg>
//               </button>
//               {isPagesOpen && (
//                 <ul className="py-2 space-y-2">
//                   <li>
//                     <Link
//                       href="#"
//                       className="flex items-center p-2 pl-11 w-full text-base font-medium text-gray-900 rounded-lg transition duration-75 group hover:bg-gray-100 dark:text-white dark:hover:bg-gray-700"
//                     >
//                       Settings
//                     </Link>
//                   </li>
//                   <li>
//                     <Link
//                       href="#"
//                       className="flex items-center p-2 pl-11 w-full text-base font-medium text-gray-900 rounded-lg transition duration-75 group hover:bg-gray-100 dark:text-white dark:hover:bg-gray-700"
//                     >
//                       Kanban
//                     </Link>
//                   </li>
//                   <li>
//                     <Link
//                       href="#"
//                       className="flex items-center p-2 pl-11 w-full text-base font-medium text-gray-900 rounded-lg transition duration-75 group hover:bg-gray-100 dark:text-white dark:hover:bg-gray-700"
//                     >
//                       Calendar
//                     </Link>
//                   </li>
//                 </ul>
//               )}
//             </li>
//             {/* Add other sidebar items similarly */}
//           </ul>
//           <ul className="pt-5 mt-5 space-y-2 border-t border-gray-200 dark:border-gray-700">
//             <li>
//               <Link
//                 href="#"
//                 className="flex items-center p-2 text-base font-medium text-gray-900 rounded-lg transition duration-75 hover:bg-gray-100 dark:hover:bg-gray-700 dark:text-white group"
//               >
//                 <svg
//                   className="flex-shrink-0 w-6 h-6 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white"
//                   fill="currentColor"
//                   viewBox="0 0 20 20"
//                   xmlns="http://www.w3.org/2000/svg"
//                 >
//                   <path d="M9 2a1 1 0 000 2h2a1 1 0 100-2H9z"></path>
//                   <path
//                     fillRule="evenodd"
//                     d="M4 5a2 2 0 012-2 3 3 0 003 3h2a3 3 0 003-3 2 2 0 012 2v11a2 2 0 01-2 2H6a2 2 0 01-2-2V5zm3 4a1 1 0 000 2h.01a1 1 0 100-2H7zm3 0a1 1 0 000 2h3a1 1 0 100-2h-3zm-3 4a1 1 0 100 2h.01a1 1 0 100-2H7zm3 0a1 1 0 100 2h3a1 1 0 100-2h-3z"
//                     clipRule="evenodd"
//                   ></path>
//                 </svg>
//                 <span className="ml-3">Docs</span>
//               </Link>
//             </li>
//             {/* Add other bottom sidebar items */}
//           </ul>
//         </div>
//         <div className="hidden absolute bottom-0 left-0 justify-center p-4 space-x-4 w-full lg:flex bg-white dark:bg-gray-800 z-20">
//           <Link
//             href="#"
//             className="inline-flex justify-center p-2 text-gray-500 rounded cursor-pointer dark:text-gray-400 hover:text-gray-900 dark:hover:text-white hover:bg-gray-100 dark:hover:bg-gray-600"
//           >
//             <svg
//               className="w-6 h-6"
//               fill="currentColor"
//               viewBox="0 0 20 20"
//               xmlns="http://www.w3.org/2000/svg"
//             >
//               <path d="M5 4a1 1 0 00-2 0v7.268a2 2 0 000 3.464V16a1 1 0 102 0v-1.268a2 2 0 000-3.464V4zM11 4a1 1 0 10-2 0v1.268a2 2 0 000 3.464V16a1 1 0 102 0V8.732a2 2 0 000-3.464V4zM16 3a1 1 0 011 1v7.268a2 2 0 010 3.464V16a1 1 0 11-2 0v-1.268a2 2 0 010-3.464V4a1 1 0 011-1z"></path>
//             </svg>
//           </Link>
//           <Link
//             href="#"
//             className="inline-flex justify-center p-2 text-gray-500 rounded cursor-pointer dark:text-gray-400 dark:hover:text-white hover:text-gray-900 hover:bg-gray-100 dark:hover:bg-gray-600"
//           >
//             <svg
//               className="w-6 h-6"
//               fill="currentColor"
//               viewBox="0 0 20 20"
//               xmlns="http://www.w3.org/2000/svg"
//             >
//               <path
//                 fillRule="evenodd"
//                 d="M11.49 3.17c-.38-1.56-2.6-1.56-2.98 0a1.532 1.532 0 01-2.286.948c-1.372-.836-2.942.734-2.106 2.106.54.886.061 2.042-.947 2.287-1.561.379-1.561 2.6 0 2.978a1.532 1.532 0 01.947 2.287c-.836 1.372.734 2.942 2.106 2.106a1.532 1.532 0 012.287.947c.379 1.561 2.6 1.561 2.978 0a1.533 1.533 0 012.287-.947c1.372.836 2.942-.734 2.106-2.106a1.533 1.533 0 01.947-2.287c1.561-.379 1.561-2.6 0-2.978a1.532 1.532 0 01-.947-2.287c.836-1.372-.734-2.942-2.106-2.106a1.532 1.532 0 01-2.287-.947zM10 13a3 3 0 100-6 3 3 0 000 6z"
//                 clipRule="evenodd"
//               ></path>
//             </svg>
//           </Link>
//           <button
//             onClick={toggleLanguage}
//             className="inline-flex justify-center p-2 text-gray-500 rounded cursor-pointer dark:hover:text-white dark:text-gray-400 hover:text-gray-900 hover:bg-gray-100 dark:hover:bg-gray-600"
//           >
//             <svg
//               className="h-5 w-5 rounded-full mt-0.5"
//               viewBox="0 0 3900 3900"
//               xmlns="http://www.w3.org/2000/svg"
//             >
//               <path fill="#b22234" d="M0 0h7410v3900H0z" />
//               <path
//                 d="M0 450h7410m0 600H0m0 600h7410m0 600H0m0 600h7410m0 600H0"
//                 stroke="#fff"
//                 strokeWidth="300"
//               />
//               <path fill="#3c3b6e" d="M0 0h2964v2100H0z" />
//               <g fill="#fff">
//                 <g id="d">
//                   <g id="c">
//                     <g id="e">
//                       <g id="b">
//                         <path
//                           id="a"
//                           d="M247 90l70.534 217.082-184.66-134.164h228.253L176.466 307.082z"
//                         />
//                         <use xlinkHref="#a" y="420" />
//                         <use xlinkHref="#a" y="840" />
//                         <use xlinkHref="#a" y="1260" />
//                       </g>
//                       <use xlinkHref="#a" y="1680" />
//                     </g>
//                     <use xlinkHref="#b" x="247" y="210" />
//                   </g>
//                   <use xlinkHref="#c" x="494" />
//                 </g>
//                 <use xlinkHref="#d" x="988" />
//                 <use xlinkHref="#c" x="1976" />
//                 <use xlinkHref="#e" x="2470" />
//               </g>
//             </svg>
//           </button>
//           {isLanguageOpen && (
//             <div className="absolute bottom-12 left-0 z-50 my-4 text-base list-none bg-white rounded divide-y divide-gray-100 shadow dark:bg-gray-700">
//               <ul className="py-1">
//                 <li>
//                   <Link
//                     href="#"
//                     className="block py-2 px-4 text-sm text-gray-700 hover:bg-gray-100 dark:hover:text-white dark:text-gray-300 dark:hover:bg-gray-600"
//                   >
//                     <div className="inline-flex items-center">
//                       <svg
//                         className="h-3.5 w-3.5 rounded-full mr-2"
//                         viewBox="0 0 512 512"
//                         xmlns="http://www.w3.org/2000/svg"
//                       >
//                         <g fillRule="evenodd">
//                           <g strokeWidth="1pt">
//                             <path
//                               fill="#bd3d44"
//                               d="M0 0h247v10H0zm0 20h247v10H0zm0 20h247v10H0zm0 20h247v10H0zm0 20h247v10H0zm0 20h247v10H0zm0 20h247v10H0z"
//                               transform="scale(3.9385)"
//                             />
//                             <path
//                               fill="#fff"
//                               d="M0 10h247v10H0zm0 20h247v10H0zm0 20h247v10H0zm0 20h247v10H0zm0 20h247v10H0zm0 20h247v10H0z"
//                               transform="scale(3.9385)"
//                             />
//                           </g>
//                           <path
//                             fill="#192f5d"
//                             d="M0 0h98.8v70H0z"
//                             transform="scale(3.9385)"
//                           />
//                         </g>
//                       </svg>
//                       English (US)
//                     </div>
//                   </Link>
//                 </li>
//                 {/* Add other language items */}
//               </ul>
//             </div>
//           )}
//         </div>
//       </aside>
// 
//       {/* Main Content */}
//       <main className="p-4 md:ml-64 h-auto pt-20">{children}</main>
//     </div>
//   );
// }