// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Nav } from "@/components/Navbar";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Nail App",
  description: "Generated by shirin joon",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
<Nav/>
        {children}
      </body>
    </html>
  );
}


